export const cryptos = [
    {
        id: 1,
        title: "Bitcoin Mining",
        description: "Bitcoin is a decentralized digital currency that can be transferred on the peer-to-peer bitcoin network. Bitcoin transactions are verified by network nodes through cryptography and recorded in a public distributed ledger called a blockchain. A type of digital currency in which a record of transactions is maintained and new units of currency are generated by the computational solution of mathematical problems, and which operates independently of a central bank",
        imgUrl:"/pricing/images/crypto1.jpg"
        
    },



      {
        id: 2,
        title: "Nft",
        description:"A non-fungible token is a unique digital identifier that cannot be copied, substituted, or subdivided, that is recorded in a blockchain, and that is used to certify authenticity and ownership. NFTs or non-fungible tokens are digital assets based on blockchain technology. Anything can become an NFT—a piece of art, sports memorabilia, or even a tweet. " ,
        imgUrl:"/pricing/images/crypto2.jpg"
        
    },

      
      
        {
        id: 3,
        title: "Ethereum",
        description: "Ethereum is a decentralized, open-source blockchain with smart contract functionality. Ether is the native cryptocurrency of the platform. Among cryptocurrencies, ether is second only to bitcoin in market capitalization. Ethereum was conceived in 2013 by programmer Vitalik Buterin",
        imgUrl:"/pricing/images/crypto3.jpg"
        
    },
]

